server:
  port: 18082
spring.application.name: demo
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/localhost?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server.error.include-message: always
server.error.include-binding-errors: always
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourpackage: TRACE
  file:
    path: logs/myapp.log
    backup:
      path: logs/myapp.log.zip
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
